package za.co.duze.orders;

public enum OrderStatus {
    CREATED, PAYMENT_PENDING, PLACED, MERCHANT_ACCEPTED, PREPARING,
    RIDER_SEARCHING, RIDER_ASSIGNED, READY_FOR_PICKUP, RIDER_AT_PICKUP,
    PICKED_UP, OUT_FOR_DELIVERY, DELIVERED, REJECTED, CANCELLED,
    DELIVERY_FAILED, REFUND_PENDING, REFUNDED
}
